### ISSUE TITLE
Target net5.0

### ISSUE THREAD

**Issue by r-work** [samhocevar/emoji.wpf#24]
At the moment referencing package in net5.0 WPF app I get the following warning:

**Package 'Emoji.Wpf 0.1.5' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.**

Though it works without an issue, it would be nice to target net5.0 as well.
Thanks.

**Comment by samhocevar** [comment]
Thanks for reporting this. Are you familiar with that kind of issue? I just put `<TargetFrameworkVersion>v3.0</TargetFrameworkVersion>` in the `.csproj` file to ensure maximum backwards compatibility, so I don’t really know how that causes it to work with 4.8 but not 5.0.

**Comment by r-work** [comment]
As mentioned, it works with no issues with net5.0, I can only assume that it needs explicitly target net5.0, hence the warning.

**Comment by samhocevar** [comment]
Yes, sorry, by “work” I meant “not issue a warning”.

I target `net30` which as far as I understand should be compatible with virtually anything. I’m tagging this issue as “help wanted” because [I target .NET 3.0 in the `.csproj`](https://github.com/samhocevar/emoji.wpf/blob/v0.1.7/Emoji.Wpf/Emoji.Wpf.csproj#L31) and [put all extra libraries in `lib/net30`](https://github.com/samhocevar/emoji.wpf/blob/v0.1.7/Emoji.Wpf/Emoji.Wpf.nuspec#L28) so I have no idea what causes the warning.

**Comment by r-work** [comment]
I'm not really sure, it could be an msbuild issue i guess.
Anyway, since it works, not exactly high priority, just thought letting you know.
Thanks for writing this library by the way.

**Comment by PsychoDad9999** [comment]
.NET 5 is the successor to .NET **Core** 3.1 and not targeting compatible with .NET **Framework** 4.8.

https://docs.microsoft.com/en-us/dotnet/standard/frameworks
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

**Comment by virzak** [comment]
#32 fixes this, please take it for a spin
