### ISSUE TITLE
EmojiData.MatchMultiple is deleted 

### ISSUE THREAD

**Issue by alluLinger** [samhocevar/emoji.wpf#44]
after this update 1c22cf7847be6953172a50660a8cb31e8026a8b2 MatchMultiple is unuseable,
Is there any alternative func?

**Comment by samhocevar** [comment]
It was removed because it was really too computationally intensive, had to be recompiled after each call to `RegisterEmoji()`, and was no longer used inside the library. 

Can you maybe explain why you were using it? If there a use case for it, I can add it back. But note that you can easily create a similar regex using:

    var MatchMultiple = new Regex(Emoji.Wpf.EmojiData.MatchOne.ToString() + "+");

**Comment by alluLinger** [comment]
sorry, take too long to reply. just using in some old code in work. I removed it.
