### ISSUE TITLE
Doesn't seem to work. What am I doing wrong?

### ISSUE THREAD

**Issue by mike-ward** [samhocevar/emoji.wpf#46]
Added to my WPF project and updated .XAML accordingly. Still seeing b/w emojis.

![image](https://user-images.githubusercontent.com/567927/121377875-53560600-c908-11eb-8038-d5c1d6d2baca.png)

I pushed my code to https://github.com/mike-ward/tweetz (master branch).

Maybe someone can point out the error of my ways? 😕 

Running on Windows 10

**Comment by samhocevar** [comment]
This is because the library is hooked on the dependency property for `TextBlock.Text`, whereas you are using inline objects such as `<Run>`. I am prototyping fixes for the problem.

**Comment by samhocevar** [comment]
Not sure if you are still interested, but there are new features in Emoji.Wpf v0.3.4 that make it now very easy.

In `FlowContentService.cs` I just modified the `Run()` method so that it calls `SubstituteGlyphs()` when the `Run` is inserted in a document:

```c#
private static Run Run(string text)
{
    var run = new Run(ConvertXmlEntities(text));
    run.Loaded += (o, e) => (o as Run).SubstituteGlyphs();
    return run;
}
```

This is the result:

![image](https://user-images.githubusercontent.com/245089/210409574-3c7bd0b1-f385-4985-b6bb-c5b4554bcda9.png)

**Comment by mike-ward** [comment]
Much nicer. I am noticing a performance hit on rendering. Scrolling is my program is janky when using Emoji.Wpf

**Comment by samhocevar** [comment]
I noticed that, too. The profiling tools I have access to have much improved and I am currently having a closer look at performance. There have already been improvements (see #63) but unfortunately I don’t think they will apply to Tweetz.

**Comment by mike-ward** [comment]
I peeked at your code and didn't see anything obvious. that could be improved. The emoji rendering is pretty expensive I imagine. Thanks for efforts.

**Comment by samhocevar** [comment]
FYI I have created a new sample program (`Samples/LoremIpsum.csproj`) to stress test `TextBlock` in a virtualised listbox. I believe its behaviour is very close to Tweetz, so I’ll focus on optimising that.

I will close this issue because it is not directly related to performance, but you’ll be able to track progress in #63.

**Comment by wegylexy** [comment]
Reusing a `<Run>` by changing its `.Text` and then invoking `.SubstituteGlyphs()` does not clean up previous substituted glyphs but accumulate residues.
